version: '3'
services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb-loqui
    ports:
      - "27017:27017"
  neo4j:
    image: neo4j:latest
    restart: always
    container_name: neo4j-loqui
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
  kafka:
    image: docker.io/bitnami/kafka:3.4
    restart: always
    container_name: kafka-loqui
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  redis:
    image: redis:latest
    restart: always
    container_name: redis-loqui
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_data:/data

volumes:
  kafka_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    driver: bridge