name: Build Java Project

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/users
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Get Settings.xml
      env:
        READ_FILES_TOKEN: ${{ secrets.READ_FILES_TOKEN }}
      run: |
        curl -H "Authorization: token ${READ_FILES_TOKEN}" -o settings.xml https://raw.githubusercontent.com/nancho313/loqui-devops/main/workflows/java/settings.xml

    - name: Build with Maven
      run: mvn test --file pom.xml -s $GITHUB_WORKSPACE/code/users/settings.xml
      env:
        MVN_USERNAME: nancho313
        MVN_PASSWORD: ${{ secrets.LOQUI_POM_TOKEN }}

