name: Build Java Project

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/users
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}
        cache: 'maven'

    - name: Get Settings.xml
      env:
        READ_FILES_TOKEN: ${{ secrets.READ_FILES_TOKEN }}
      run: |
        curl -H "Authorization: token ${READ_FILES_TOKEN}" -o settings.xml https://raw.githubusercontent.com/nancho313/loqui-devops/main/workflows/java/settings.xml

    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Build with Maven
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=nancho313_loqui-users -s $GITHUB_WORKSPACE/code/users/settings.xml
      env:
        MVN_USERNAME: nancho313
        MVN_PASSWORD: ${{ secrets.LOQUI_POM_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
