name: Publish Docker Image

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: loqui-users
  IMAGE_VERSION: 1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/users
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Get Settings.xml
      env:
        READ_FILES_TOKEN: ${{ secrets.READ_FILES_TOKEN }}
      run: |
        curl -H "Authorization: token ${READ_FILES_TOKEN}" -o settings.xml https://raw.githubusercontent.com/nancho313/loqui-devops/main/workflows/java/settings.xml

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build artifact
      run: mvn -B package -DskipTests -s $GITHUB_WORKSPACE/code/users/settings.xml
      env:
        MVN_USERNAME: nancho313
        MVN_PASSWORD: ${{ secrets.LOQUI_POM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: docker build . --tag ${{ env.REGISTRY }}/nancho313/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image
      run: docker push ${{ env.REGISTRY }}/nancho313/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
